<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-09T18:40:01 IST" name="Default suite" finished-at="2023-06-09T18:40:03 IST" duration-ms="1671">
    <groups>
    </groups>
    <test started-at="2023-06-09T18:40:01 IST" name="Default test" finished-at="2023-06-09T18:40:03 IST" duration-ms="1671">
      <class name="practice.Map_DataProvider">
        <test-method signature="getData(java.util.Map)[pri:0, instance:practice.Map_DataProvider@1af2d44a]" started-at="2023-06-09T18:40:03 IST" name="getData" data-provider="multipleData" finished-at="2023-06-09T18:40:03 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.util.Map practice.Map_DataProvider.multipleData() throws java.lang.Throwable,java.io.FileNotFoundException,java.io.IOException must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not interface java.util.Map]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.Map practice.Map_DataProvider.multipleData() throws java.lang.Throwable,java.io.FileNotFoundException,java.io.IOException must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not interface java.util.Map
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:175)
at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getData -->
      </class> <!-- practice.Map_DataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
